ANN

In [1]:
#importing necessary libraries

import numpy as np
import pandas as pd
from sklearn import preprocessing
from sklearn.model_selection import train_test_split 
from sklearn.preprocessing import StandardScaler 
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import classification_report, confusion_matrix 

In [2]:
df=pd.read_csv('iris.csv')

In [3]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   species  
0        0  
1        0  
2        0  
3        0  
4        0

In [5]:
#removing the last column i.e. the target variable column
x=df.iloc[:,0:4] 

In [6]:
x.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [7]:
y=df.select_dtypes(include=[object])

In [8]:
y.head()

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4]

In [11]:
#Checking out unique values
y.Class

AttributeError: 'DataFrame' object has no attribute 'Class'

In [12]:
#Splitting into train and test
x_train,x_test,y_train,y_test=train_test_split(x, y, test_size=0.20)

In [13]:
#Performing feauture scaling
ss=StandardScaler() 
ss.fit(x_train) 
x_train = ss.transform(x_train) 
x_test = ss.transform(x_test)

In [15]:
#Building the model
mlp_classifier = MLPClassifier(hidden_layer_sizes=(10, 10, 10), max_iter=1000) 
mlp_classifier.fit(x_train, y_train.values.ravel())

ValueError: Found array with 0 sample(s) (shape=(0,)) while a minimum of 1 is required.

In [16]:
#importing the dataset
from sklearn.datasets import load_iris
df=load_iris()

In [19]:
df

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [20]:
x=df.data
y=df.target

In [21]:
x

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [22]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [23]:
#Splitting into train and test
x_train,x_test,y_train,y_test=train_test_split(x, y, test_size=0.20)

In [24]:
#Performing feauture scaling
ss=StandardScaler() 
ss.fit(x_train) 
x_train = ss.transform(x_train) 
x_test = ss.transform(x_test)

In [25]:
x_test

array([[-0.0236966 , -0.802059  ,  0.80838807,  0.9877108 ],
       [ 0.84174441, -0.11621282,  0.86548434,  1.12073582],
       [ 2.32535756,  1.71271032,  1.72192845,  1.38678587],
       [-0.51823432,  0.79824875, -1.24707777, -1.00766455],
       [-0.8891376 ,  1.02686414, -1.30417405, -1.14068957],
       [-0.51823432,  1.94132571, -1.13288523, -1.00766455],
       [-0.8891376 , -1.25928979, -0.39063367, -0.07648939],
       [-1.13640646, -1.48790518, -0.21934485, -0.20951441],
       [ 1.08901326,  0.11240257,  1.09386944,  1.65283591],
       [ 1.08901326,  0.56963335,  1.15096571,  1.25376084],
       [-0.51823432, -0.11621282,  0.46581043,  0.4556107 ],
       [-0.27096546, -1.25928979,  0.12323279, -0.07648939],
       [ 2.57262642,  1.71271032,  1.55063963,  1.12073582],
       [-0.76550317,  1.02686414, -1.24707777, -1.2737146 ],
       [ 1.08901326, -0.11621282,  0.7512918 ,  0.72166075],
       [ 0.47084112, -1.94513597,  0.46581043,  0.4556107 ],
       [ 1.33628212,  0.

In [26]:
x_train

array([[ 0.71810998, -0.57344361,  1.09386944,  1.25376084],
       [-1.38367532,  0.34101796, -1.36127032, -1.2737146 ],
       [ 0.09993783, -0.11621282,  0.29452161,  0.4556107 ],
       [ 0.71810998, -0.57344361,  1.09386944,  1.38678587],
       [-1.13640646,  1.25547953, -1.30417405, -1.40673962],
       [-0.39459989, -1.25928979,  0.18032906,  0.18956066],
       [ 0.34720669, -0.57344361,  0.58000298,  0.05653563],
       [-1.26004089, -0.11621282, -1.30417405, -1.14068957],
       [ 0.71810998,  0.11240257,  1.03677316,  0.85468577],
       [-0.39459989,  1.02686414, -1.36127032, -1.2737146 ],
       [ 0.71810998,  0.34101796,  0.92258062,  1.51981089],
       [-0.51823432,  1.48409493, -1.24707777, -1.2737146 ],
       [ 1.33628212,  0.11240257,  0.80838807,  1.51981089],
       [ 0.59447555,  0.79824875,  1.09386944,  1.65283591],
       [-1.01277203,  0.34101796, -1.41836659, -1.2737146 ],
       [-0.14733103,  1.71271032, -1.13288523, -1.14068957],
       [-0.76550317, -0.

In [28]:
#Building the model
mlp_classifier = MLPClassifier(hidden_layer_sizes=(10, 10, 10), max_iter=1000) 
mlp_classifier.fit(x_train, y_train)

MLPClassifier(hidden_layer_sizes=(10, 10, 10), max_iter=1000)

In [34]:
#Making predictions
Prediction=mlp_classifier.predict(x_test)

In [35]:
#Evaluating the model
print(confusion_matrix(y_test,Prediction)) 

[[ 8  0  0]
 [ 0  8  1]
 [ 0  1 12]]


In [36]:
print(classification_report(y_test,Prediction))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         8
           1       0.89      0.89      0.89         9
           2       0.92      0.92      0.92        13

    accuracy                           0.93        30
   macro avg       0.94      0.94      0.94        30
weighted avg       0.93      0.93      0.93        30



SVM

In [41]:
#Importing the dataset
from sklearn.datasets import load_digits
df=load_digits()

In [42]:
df

{'data': array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ..., 10.,  0.,  0.],
        [ 0.,  0.,  0., ..., 16.,  9.,  0.],
        ...,
        [ 0.,  0.,  1., ...,  6.,  0.,  0.],
        [ 0.,  0.,  2., ..., 12.,  0.,  0.],
        [ 0.,  0., 10., ..., 12.,  1.,  0.]]),
 'target': array([0, 1, 2, ..., 8, 9, 8]),
 'frame': None,
 'feature_names': ['pixel_0_0',
  'pixel_0_1',
  'pixel_0_2',
  'pixel_0_3',
  'pixel_0_4',
  'pixel_0_5',
  'pixel_0_6',
  'pixel_0_7',
  'pixel_1_0',
  'pixel_1_1',
  'pixel_1_2',
  'pixel_1_3',
  'pixel_1_4',
  'pixel_1_5',
  'pixel_1_6',
  'pixel_1_7',
  'pixel_2_0',
  'pixel_2_1',
  'pixel_2_2',
  'pixel_2_3',
  'pixel_2_4',
  'pixel_2_5',
  'pixel_2_6',
  'pixel_2_7',
  'pixel_3_0',
  'pixel_3_1',
  'pixel_3_2',
  'pixel_3_3',
  'pixel_3_4',
  'pixel_3_5',
  'pixel_3_6',
  'pixel_3_7',
  'pixel_4_0',
  'pixel_4_1',
  'pixel_4_2',
  'pixel_4_3',
  'pixel_4_4',
  'pixel_4_5',
  'pixel_4_6',
  'pixel_4_7',
  'pixel_5_0',
  'pixel_5_1',
 

In [43]:
x=df.data
y=df.target

In [44]:
x

array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ..., 10.,  0.,  0.],
       [ 0.,  0.,  0., ..., 16.,  9.,  0.],
       ...,
       [ 0.,  0.,  1., ...,  6.,  0.,  0.],
       [ 0.,  0.,  2., ..., 12.,  0.,  0.],
       [ 0.,  0., 10., ..., 12.,  1.,  0.]])

In [45]:
y

array([0, 1, 2, ..., 8, 9, 8])

In [46]:
#Splitting into train and test
x_train,x_test,y_train,y_test=train_test_split(x, y, test_size=0.20)

In [47]:
#Building svm classifier
from sklearn.svm import SVC 
svm_classifier = SVC(kernel='linear') 
svm_classifier.fit(x_train, y_train)

SVC(kernel='linear')

In [48]:
#Making predictions
Prediction=svm_classifier.predict(x_test)

In [49]:
#Evaluating the model
print(confusion_matrix(y_test,Prediction))

[[34  0  0  0  0  0  0  0  0  0]
 [ 0 48  0  0  0  0  0  0  1  0]
 [ 0  0 31  0  0  0  0  0  0  0]
 [ 0  0  0 34  0  0  0  0  0  1]
 [ 0  0  0  0 35  0  0  0  0  0]
 [ 0  0  0  0  0 30  0  0  0  1]
 [ 0  0  0  0  0  0 39  0  0  0]
 [ 0  0  0  0  0  0  0 45  0  0]
 [ 0  0  0  0  0  0  0  0 25  0]
 [ 0  0  0  0  0  0  0  0  0 36]]


In [50]:
print(classification_report(y_test,Prediction))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        34
           1       1.00      0.98      0.99        49
           2       1.00      1.00      1.00        31
           3       1.00      0.97      0.99        35
           4       1.00      1.00      1.00        35
           5       1.00      0.97      0.98        31
           6       1.00      1.00      1.00        39
           7       1.00      1.00      1.00        45
           8       0.96      1.00      0.98        25
           9       0.95      1.00      0.97        36

    accuracy                           0.99       360
   macro avg       0.99      0.99      0.99       360
weighted avg       0.99      0.99      0.99       360



In [51]:
#Using Kernel polynomial
from sklearn.svm import SVC 
svm_classifier = SVC(kernel='poly',degree=8) 
svm_classifier.fit(x_train, y_train)

SVC(degree=8, kernel='poly')

In [52]:
#Making predictions
Prediction=svm_classifier.predict(x_test)

In [53]:
#Evaluating the model
print(confusion_matrix(y_test,Prediction))

[[33  0  0  0  0  0  1  0  0  0]
 [ 1 46  0  0  0  1  0  0  1  0]
 [ 0  0 31  0  0  0  0  0  0  0]
 [ 0  0  0 33  0  2  0  0  0  0]
 [ 0  0  0  0 35  0  0  0  0  0]
 [ 0  0  0  0  0 30  0  0  0  1]
 [ 0  0  0  0  0  0 39  0  0  0]
 [ 0  0  0  0  0  0  0 45  0  0]
 [ 0  0  0  1  0  0  0  0 24  0]
 [ 0  0  0  1  0  0  0  0  0 35]]


In [54]:
print(classification_report(y_test,Prediction))

              precision    recall  f1-score   support

           0       0.97      0.97      0.97        34
           1       1.00      0.94      0.97        49
           2       1.00      1.00      1.00        31
           3       0.94      0.94      0.94        35
           4       1.00      1.00      1.00        35
           5       0.91      0.97      0.94        31
           6       0.97      1.00      0.99        39
           7       1.00      1.00      1.00        45
           8       0.96      0.96      0.96        25
           9       0.97      0.97      0.97        36

    accuracy                           0.97       360
   macro avg       0.97      0.98      0.97       360
weighted avg       0.98      0.97      0.98       360



In [55]:
#Using gaussian kernel
#Using Kernel polynomial
from sklearn.svm import SVC 
svm_classifier = SVC(kernel='rbf') 
svm_classifier.fit(x_train, y_train)

SVC()

In [56]:
#Making predictions
Prediction=svm_classifier.predict(x_test)

In [57]:
#Evaluating the model
print(confusion_matrix(y_test,Prediction))

[[34  0  0  0  0  0  0  0  0  0]
 [ 0 49  0  0  0  0  0  0  0  0]
 [ 0  0 31  0  0  0  0  0  0  0]
 [ 0  0  0 34  0  1  0  0  0  0]
 [ 0  0  0  0 33  0  0  0  2  0]
 [ 0  0  0  0  0 30  0  0  0  1]
 [ 0  0  0  0  0  0 39  0  0  0]
 [ 0  0  0  0  0  0  0 45  0  0]
 [ 0  0  0  0  0  0  0  0 25  0]
 [ 0  0  0  0  0  0  0  0  0 36]]


In [58]:
print(classification_report(y_test,Prediction))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        34
           1       1.00      1.00      1.00        49
           2       1.00      1.00      1.00        31
           3       1.00      0.97      0.99        35
           4       1.00      0.94      0.97        35
           5       0.97      0.97      0.97        31
           6       1.00      1.00      1.00        39
           7       1.00      1.00      1.00        45
           8       0.93      1.00      0.96        25
           9       0.97      1.00      0.99        36

    accuracy                           0.99       360
   macro avg       0.99      0.99      0.99       360
weighted avg       0.99      0.99      0.99       360



In [1]:
#importing the dataset
from sklearn.datasets import load_iris
df=load_iris()

In [2]:
#importing necessary libraries

import numpy as np
import pandas as pd
from sklearn import preprocessing
from sklearn.model_selection import train_test_split 
from sklearn.preprocessing import StandardScaler 
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import classification_report, confusion_matrix 

In [3]:
df

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [4]:
x=df.data
y=df.target

In [5]:
#Splitting into train and test
x_train,x_test,y_train,y_test=train_test_split(x, y, test_size=0.20)

In [7]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)

In [8]:
x_test = sc.transform(x_test)

In [10]:
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(n_estimators=20, random_state=0) 
regressor.fit(x_train, y_train)
y_pred = regressor.predict(x_test)

In [11]:
from sklearn import metrics
print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred)) 
print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred)) 
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))

Mean Absolute Error: 0.060000000000000005
Mean Squared Error: 0.04416666666666667
Root Mean Squared Error: 0.21015867021530818


Random Forest

In [12]:
from sklearn.ensemble import RandomForestClassifier
classifier= RandomForestClassifier(n_estimators=20, random_state=0) 
classifier.fit(x_train, y_train)
y_pred = classifier.predict(x_test)

In [13]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score 
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(accuracy_score(y_test, y_pred))

[[10  0  0]
 [ 0  9  0]
 [ 0  1 10]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       0.90      1.00      0.95         9
           2       1.00      0.91      0.95        11

    accuracy                           0.97        30
   macro avg       0.97      0.97      0.97        30
weighted avg       0.97      0.97      0.97        30

0.9666666666666667


Extra Trees

In [14]:
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.datasets import make_classification

In [15]:
x, y = make_classification(n_features=4, random_state=0)

In [16]:
c = ExtraTreesClassifier(n_estimators=100, random_state=0)

In [18]:
c.fit(x, y)
ExtraTreesClassifier(random_state=0)

ExtraTreesClassifier(random_state=0)

In [22]:
c.predict([[3.6, 2.4, 1.2, 0.1]])

array([1])

Adaboost

In [23]:
#importing libraries
from sklearn.datasets import load_iris
from sklearn.ensemble import AdaBoostClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [24]:
# Load the iris dataset
iris = load_iris()
X = iris.data
y = iris.target

In [25]:
# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [26]:
dtc = DecisionTreeClassifier(max_depth=1)

In [27]:
adaboost = AdaBoostClassifier(base_estimator=dtc, n_estimators=50, learning_rate=1)

In [28]:
adaboost.fit(X_train, y_train)

AdaBoostClassifier(base_estimator=DecisionTreeClassifier(max_depth=1),
                   learning_rate=1)

In [29]:
y_pred = adaboost.predict(X_test)

In [30]:
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy: {:.2f}%".format(accuracy * 100))

Accuracy: 100.00%


Stochastic Gradient

In [31]:
from sklearn.ensemble import GradientBoostingClassifier

In [32]:
gbc = GradientBoostingClassifier(subsample=0.8, max_depth=3)

In [33]:
gbc.fit(X_train, y_train)

GradientBoostingClassifier(subsample=0.8)

In [34]:
y_pred = gbc.predict(X_test)

In [35]:
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy: {:.2f}%".format(accuracy * 100))

Accuracy: 100.00%


KNN

In [36]:
#importing libraries
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

In [37]:
# Loading the iris dataset
iris = load_iris()
X = iris.data
y = iris.target

In [38]:
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [39]:
#Spliting the dataset into training and testing sets
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=42)

In [40]:
#Creating a KNN classifier with k=3
knn = KNeighborsClassifier(n_neighbors=3)

In [41]:
knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=3)

In [42]:
# Prediction
y_pred = knn.predict(X_test)

In [43]:
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy: {:.2f}%".format(accuracy * 100))

Accuracy: 100.00%


In [44]:
# Printing the correct and wrong predictions
for i in range(len(y_pred)):
    if y_pred[i] == y_test[i]:
        print("Correct prediction: Predicted label = {}, True label = {}".format(y_pred[i], y_test[i]))
    else:
        print("Wrong prediction: Predicted label = {}, True label = {}".format(y_pred[i], y_test[i]))

Correct prediction: Predicted label = 1, True label = 1
Correct prediction: Predicted label = 0, True label = 0
Correct prediction: Predicted label = 2, True label = 2
Correct prediction: Predicted label = 1, True label = 1
Correct prediction: Predicted label = 1, True label = 1
Correct prediction: Predicted label = 0, True label = 0
Correct prediction: Predicted label = 1, True label = 1
Correct prediction: Predicted label = 2, True label = 2
Correct prediction: Predicted label = 1, True label = 1
Correct prediction: Predicted label = 1, True label = 1
Correct prediction: Predicted label = 2, True label = 2
Correct prediction: Predicted label = 0, True label = 0
Correct prediction: Predicted label = 0, True label = 0
Correct prediction: Predicted label = 0, True label = 0
Correct prediction: Predicted label = 0, True label = 0
Correct prediction: Predicted label = 1, True label = 1
Correct prediction: Predicted label = 2, True label = 2
Correct prediction: Predicted label = 1, True la

In [45]:
#importing libraries
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.ensemble import VotingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

In [46]:
iris = load_iris()
X = iris.data
y = iris.target

In [47]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [48]:
#Creating three classifiers: logistic regression, decision tree, and KNN
clf1 = LogisticRegression(random_state=42)
clf2 = DecisionTreeClassifier(random_state=42)
clf3 = KNeighborsClassifier(n_neighbors=3)

In [49]:
# Creating a voting classifier with the three classifiers
voting_clf = VotingClassifier(estimators=[('lr', clf1), ('dt', clf2), ('knn', clf3)], voting='hard')

In [50]:
voting_clf.fit(X_train, y_train)

VotingClassifier(estimators=[('lr', LogisticRegression(random_state=42)),
                             ('dt', DecisionTreeClassifier(random_state=42)),
                             ('knn', KNeighborsClassifier(n_neighbors=3))])

In [51]:
y_pred = voting_clf.predict(X_test)

In [52]:
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy: {:.2f}%".format(accuracy * 100))

Accuracy: 100.00%
