In [1]:
import numpy as np

In [4]:
arr1=np.zeros(6)
print(arr1)

[0. 0. 0. 0. 0. 0.]


In [5]:
arr2=np.ones(6)
print(arr2)

[1. 1. 1. 1. 1. 1.]


In [7]:
arr3=np.ones(6)
arr3=arr3*5
print(arr3)

[5. 5. 5. 5. 5. 5.]


In [9]:
arr4=np.arange(1,100)
print(arr4)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96
 97 98 99]


In [10]:
arr5=np.arange(1,100,2)
print(arr5)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99]


In [12]:
arr6=np.arange(1,5)
mat1=np.array(arr6).reshape(2,2)
print(mat1)

[[1 2]
 [3 4]]


In [13]:
arr7=np.arange(9,18)
mat2=arr7.reshape(3,3)
print(mat2)

[[ 9 10 11]
 [12 13 14]
 [15 16 17]]


In [14]:
identity_mat=np.eye(4)
print(identity_mat)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [19]:
num = np.random.uniform(0,1,1) #generating 1 random number
print(num)

[0.37386189]


In [20]:
num_arr = np.random.uniform(0,1,10) #generating array of 10 random numbers
print(num_arr)

[0.01396624 0.57200424 0.03674919 0.52029095 0.95569697 0.23137473
 0.22435639 0.69725734 0.6583118  0.90622458]


In [23]:
equal_space=np.linspace(1,10,10) #creating 10 equally spaced points within range of 1-10
print(equal_space)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [24]:
equal_space2=np.linspace(1,2,10) #creating 10 equally spaced points within range of 1-2
print(equal_space2)

[1.         1.11111111 1.22222222 1.33333333 1.44444444 1.55555556
 1.66666667 1.77777778 1.88888889 2.        ]


In [26]:
array=np.arange(0,100)
print("Array Before: ")
print(array)
array=array[::-1]
print("Array After: ")
print(array)

Array Before: 
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
Array After: 
[99 98 97 96 95 94 93 92 91 90 89 88 87 86 85 84 83 82 81 80 79 78 77 76
 75 74 73 72 71 70 69 68 67 66 65 64 63 62 61 60 59 58 57 56 55 54 53 52
 51 50 49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28
 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4
  3  2  1  0]


In [32]:
matrix=np.arange(0,400)
matrix=matrix.reshape(20,20)
print("20 x 20 Matrix: ")
print(matrix)

20 x 20 Matrix: 
[[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
   18  19]
 [ 20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36  37
   38  39]
 [ 40  41  42  43  44  45  46  47  48  49  50  51  52  53  54  55  56  57
   58  59]
 [ 60  61  62  63  64  65  66  67  68  69  70  71  72  73  74  75  76  77
   78  79]
 [ 80  81  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97
   98  99]
 [100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117
  118 119]
 [120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137
  138 139]
 [140 141 142 143 144 145 146 147 148 149 150 151 152 153 154 155 156 157
  158 159]
 [160 161 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177
  178 179]
 [180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
  198 199]
 [200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215 216 217
  218 219]
 [220 221 222 223 224 225 226 227 228 229 230 23

In [33]:
print("Minimum element in Matrix: ")
print(np.min(matrix))
print("Maximum element in Matrix: ")
print(np.max(matrix))

Minimum element in Matrix: 
0
Maximum element in Matrix: 
399


In [38]:
rand_arr=np.random.randint(0,100,50)
print("Randomly generated array: ")
print(rand_arr)
print("Mean Value: ")
print(np.mean(rand_arr))

Randomly generated array: 
[30 41 78 18  0 68 58 32 74  3 63 84 60 21 98 54 54 83 32 77 62 79 81  0
  8 33 35 12 37 76 43 99 77  5 10 32 71 35 87 73 58 19 56 62 40 85 55 76
 54 53]
Mean Value: 
50.82


In [42]:
array20x20=np.zeros(400)
array20x20=array20x20.reshape(20,20)
array20x20[1:-1,1:-1]=1
print(array20x20)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.

In [52]:
array8x8=np.zeros(64)
array8x8=array8x8.reshape(8,8)
array8x8[1::2,0::2]=1
#print(array8x8)
array8x8[0::2,1::2]=1
print(array8x8)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [59]:
lower_diag=np.array([9,8,7])
array4x4=np.diag(lower_diag,-1)
print(array4x4)

[[0 0 0 0]
 [9 0 0 0]
 [0 8 0 0]
 [0 0 7 0]]


In [72]:
array10x10=np.ones((10,10)) #creating a 10 by 10 array
np.put(array10x10,np.random.choice(range(10*10),10,replace=False),np.nan) #This will randomly make 10 elements as nan
print(array10x10)

[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1. nan  1. nan]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1. nan  1.  1.  1.  1. nan  1.  1.  1.]
 [nan  1. nan nan  1.  1.  1.  1.  1. nan]
 [ 1.  1.  1.  1.  1. nan  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1. nan  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]]


In [74]:
null_vector=np.zeros(20)
print("Null Vector:")
print(null_vector)
null_vector[6]=11 
print("Null Vector After Updating:")
print(null_vector)

Null Vector:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Null Vector After Updating:
[ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.]


In [81]:
a=np.array([20,30,40])
print(a.dtype)

int32


In [82]:
b=np.array([2.1,0.8,1.0])
print(b.dtype)

float64


In [83]:
print(np.dtype(np.int32))

int32


In [84]:
print(np.dtype(np.float64))

float64


In [92]:
arr1=np.random.randint(0,2,9).reshape(3,3) #will create an array of 0's and 1's randomly
print(arr1)

[[1 0 1]
 [1 0 0]
 [0 1 1]]


In [93]:
arr2=np.random.randint(0,2,9).reshape(3,3) #will create an array of 0's and 1's randomly
print(arr2)

[[0 0 1]
 [1 0 0]
 [1 0 1]]


In [94]:
result=(arr1==arr2)
print(result)

[[False  True  True]
 [ True  True  True]
 [False False  True]]


In [99]:
import pandas as pd

In [100]:
list1=["New Delhi","Tamil Nadu","Haryana","Punjab","Karnataka","Kerela","Rajasthan","Gujarat","Maharashtra"]
serie=pd.Series(list1)
print(serie)

0      New Delhi
1     Tamil Nadu
2        Haryana
3         Punjab
4      Karnataka
5         Kerela
6      Rajasthan
7        Gujarat
8    Maharashtra
dtype: object


In [101]:
dict1={'Apples':20,'Oranges':30,'Banana':12,'Guava':25,'Mango':32,'Kiwi':15,'Litchi':8}
serie2=pd.Series(dict1)
print(serie2)

Apples     20
Oranges    30
Banana     12
Guava      25
Mango      32
Kiwi       15
Litchi      8
dtype: int64


In [109]:
arr_rand=np.random.random(10)
s4=pd.Series(arr_rand)
print(s4)

0    0.092323
1    0.611331
2    0.560451
3    0.132824
4    0.895904
5    0.213640
6    0.799061
7    0.617595
8    0.570680
9    0.565139
dtype: float64


In [110]:
arr_rand2=np.random.randint(0,100,10)
s5=pd.Series(arr_rand2)
print(s5)

0    52
1    47
2    93
3    86
4    68
5    12
6    17
7    10
8    67
9    58
dtype: int32


In [111]:
arr_rand3=np.random.normal(size=10)
s6=pd.Series(arr_rand3)
print(s6)

0    0.206022
1    1.754976
2   -1.656479
3   -1.752250
4    1.317898
5   -1.957072
6    0.970163
7    0.648281
8   -0.706277
9   -0.356905
dtype: float64


In [112]:
arr_rand4=np.linspace(0,1,10)
s7=pd.Series(arr_rand4)
print(s7)

0    0.000000
1    0.111111
2    0.222222
3    0.333333
4    0.444444
5    0.555556
6    0.666667
7    0.777778
8    0.888889
9    1.000000
dtype: float64


In [113]:
ser=pd.Series(dict1)
print(ser)

Apples     20
Oranges    30
Banana     12
Guava      25
Mango      32
Kiwi       15
Litchi      8
dtype: int64


In [114]:
ind=ser.index
print(ind)

Index(['Apples', 'Oranges', 'Banana', 'Guava', 'Mango', 'Kiwi', 'Litchi'], dtype='object')


In [115]:
val=ser.values
print(val)

[20 30 12 25 32 15  8]


In [117]:
data=[2,65,17,39,3,4,71,5,6,1,23,76,13,62,19,55,9,41,8,15]
index=['A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T']
Ser5=pd.Series(data,index)
print(Ser5)

A     2
B    65
C    17
D    39
E     3
F     4
G    71
H     5
I     6
J     1
K    23
L    76
M    13
N    62
O    19
P    55
Q     9
R    41
S     8
T    15
dtype: int64


In [118]:
Ser5.head()

A     2
B    65
C    17
D    39
E     3
dtype: int64

In [119]:
Ser5.tail()

P    55
Q     9
R    41
S     8
T    15
dtype: int64

In [121]:
#Specifying an index while creating panda series
Student_name=['Mary','John','Lily','Arnie','Elizabeth','Ester','Mike','Jack']
Roll_no=[7,5,6,1,2,3,8,4]
stud_serie=pd.Series(Student_name,index=Roll_no)
print(stud_serie)

7         Mary
5         John
6         Lily
1        Arnie
2    Elizabeth
3        Ester
8         Mike
4         Jack
dtype: object


In [153]:
stud_details=[('Nitika',21,'Mech.','20BME2029'),('Lipika',20,'CSE','20BCE2029'),
              ('Lipika',20,'CSE','20BCE2029'),('Arun',19,'ECE','20ECE2029'),
              ('Ahaan',20,'CSE','20BCE2029'),('Meeha',20,'BioTech','20BBB2029'),
             ('Meeha',20,'BioTech','20BBB2029'),('Isha',19,'CSE','20BCE2029'),
             ('Ram',21,'Civil','20BCC2029'),
             ('Shyam',21,'Mech.','20BME2029'),('Sita',20,'ECE','20ECE2029')]
col=['Name','Age','Branch','Roll Number']
df=pd.DataFrame(stud_details,columns=col)
print(df)

      Name  Age   Branch Roll Number
0   Nitika   21    Mech.   20BME2029
1   Lipika   20      CSE   20BCE2029
2   Lipika   20      CSE   20BCE2029
3     Arun   19      ECE   20ECE2029
4    Ahaan   20      CSE   20BCE2029
5    Meeha   20  BioTech   20BBB2029
6    Meeha   20  BioTech   20BBB2029
7     Isha   19      CSE   20BCE2029
8      Ram   21    Civil   20BCC2029
9    Shyam   21    Mech.   20BME2029
10    Sita   20      ECE   20ECE2029


In [154]:
#row duplicates
dupl=df[df.duplicated()]
print(dupl)

     Name  Age   Branch Roll Number
2  Lipika   20      CSE   20BCE2029
6   Meeha   20  BioTech   20BBB2029


In [155]:
dupl1=df[df.duplicated(keep='last')]
print(dupl1)

     Name  Age   Branch Roll Number
1  Lipika   20      CSE   20BCE2029
5   Meeha   20  BioTech   20BBB2029


In [143]:
#columns
dup_col=df[df.duplicated('Branch')]
print(dup_col)

     Name  Age Branch Roll Number
3   Ahaan   20    CSE   20BCE2029
5    Isha   19    CSE   20BCE2029
6  Lipika   20    CSE   20BCE2029
8   Shyam   21  Mech.   20BME2029
9    Sita   20    ECE   20ECE2029


In [144]:
dup_col1=df[df.duplicated('Age')]
print(dup_col1)

     Name  Age   Branch Roll Number
3   Ahaan   20      CSE   20BCE2029
4   Meeha   20  BioTech   20BBB2029
5    Isha   19      CSE   20BCE2029
6  Lipika   20      CSE   20BCE2029
7     Ram   21    Civil   20BCC2029
8   Shyam   21    Mech.   20BME2029
9    Sita   20      ECE   20ECE2029


In [145]:
dup_col2=df[df.duplicated(['Branch','Age'])]
print(dup_col2)

     Name  Age Branch Roll Number
3   Ahaan   20    CSE   20BCE2029
6  Lipika   20    CSE   20BCE2029
8   Shyam   21  Mech.   20BME2029


In [146]:
print(len(stud_serie))

8


In [147]:
print(stud_serie.size)

8


In [148]:
print(stud_serie.shape)

(8,)


In [150]:
# Import pandas library
import pandas as pd
  
# List of Tuples
employees = [('Stuti', 28, 'Varanasi'),
            ('Saumya', 32, 'Delhi'),
            ('Aaditya', 25, 'Mumbai'),
            ('Saumya', 32, 'Delhi'),
            ('Saumya', 32, 'Delhi'),
            ('Saumya', 32, 'Mumbai'),
            ('Aaditya', 40, 'Dehradun'),
            ('Seema', 32, 'Delhi')
            ]
  
# Creating a DataFrame object
df = pd.DataFrame(employees, 
                  columns = ['Name', 'Age', 'City'])
  
# Print the Dataframe
print(df)


      Name  Age      City
0    Stuti   28  Varanasi
1   Saumya   32     Delhi
2  Aaditya   25    Mumbai
3   Saumya   32     Delhi
4   Saumya   32     Delhi
5   Saumya   32    Mumbai
6  Aaditya   40  Dehradun
7    Seema   32     Delhi


In [151]:
duplicate = df[df.duplicated()]
print(duplicate)

     Name  Age   City
3  Saumya   32  Delhi
4  Saumya   32  Delhi


In [1]:
import pandas as pd
import numpy as np

In [7]:
#Creating raw data
ht=np.random.uniform(4.7,6.5,40) # Height Values in ft ranging from 4.7ft-6.5ft
wt=np.random.uniform(50000,100000,40) # Weight Values in grams ranging from 50,000g(50kg)-100,000(100kg)
df=pd.DataFrame()
df['Height']=ht
df['Weight']=wt
print(df)

      Height        Weight
0   6.476419  98262.042170
1   6.480759  57257.731850
2   5.009157  92505.208004
3   4.974122  66334.897474
4   6.292070  76051.338351
5   5.096848  59079.721936
6   6.369597  95578.370212
7   5.277186  85529.872938
8   5.500884  51467.446870
9   5.609744  72097.493058
10  6.487972  97466.836843
11  5.442534  80152.041101
12  5.848103  91726.461700
13  4.897932  92382.726781
14  5.845120  52395.985538
15  6.167873  57874.166929
16  4.897806  53608.192099
17  5.462671  85396.493252
18  5.386413  92315.267437
19  4.958338  73724.453245
20  6.378715  68867.352917
21  4.892325  58922.405236
22  6.065894  77952.490552
23  4.779468  90868.923476
24  6.196348  66281.075297
25  5.878887  74030.834190
26  5.965006  76080.438734
27  5.424634  65831.064041
28  5.766342  99218.441389
29  4.898722  78663.633954
30  5.555791  70435.303581
31  4.847733  65657.307516
32  5.016774  55072.252758
33  4.913045  79847.238231
34  4.980025  83100.094840
35  5.376071  90675.355154
3

In [8]:
#MinMax normalisation
from sklearn.preprocessing import MinMaxScaler 
sc = MinMaxScaler(feature_range=(-10, 10)) 
df1=df
df1[['Weight']] = sc.fit_transform(df1[['Weight']])
print(df1)


      Height     Weight
0   6.476419   9.599422
1   6.480759  -7.574800
2   5.009157   7.188233
3   4.974122  -3.772925
4   6.292070   0.296703
5   5.096848  -6.811679
6   6.369597   8.475395
7   5.277186   4.266688
8   5.500884 -10.000000
9   5.609744  -1.359323
10  6.487972   9.266359
11  5.442534   2.014240
12  5.848103   6.862063
13  4.897932   7.136933
14  5.845120  -9.611091
15  6.167873  -7.316613
16  4.897806  -9.103371
17  5.462671   4.210823
18  5.386413   7.108678
19  4.958338  -0.677888
20  6.378715  -2.712233
21  4.892325  -6.877569
22  6.065894   1.092981
23  4.779468   6.502893
24  6.196348  -3.795468
25  5.878887  -0.549563
26  5.965006   0.308892
27  5.424634  -3.983951
28  5.766342  10.000000
29  4.898722   1.390836
30  5.555791  -2.055513
31  4.847733  -4.056727
32  5.016774  -8.490165
33  4.913045   1.886576
34  4.980025   3.249001
35  5.376071   6.421819
36  5.772103  -1.684780
37  6.157824  -7.678349
38  4.726864   8.414526
39  6.311262  -5.801219


In [9]:
#Z score normalisation
from sklearn.preprocessing import StandardScaler
df2=df
sc = StandardScaler() 
df2[['Weight']] = sc.fit_transform(df2[['Weight']])
print(df2)

      Height    Weight
0   6.476419  1.568546
1   6.480759 -1.250791
2   5.009157  1.172723
3   4.974122 -0.626672
4   6.292070  0.041403
5   5.096848 -1.125516
6   6.369597  1.384025
7   5.277186  0.693119
8   5.500884 -1.648914
9   5.609744 -0.230452
10  6.487972  1.513870
11  5.442534  0.323355
12  5.848103  1.119179
13  4.897932  1.164301
14  5.845120 -1.585071
15  6.167873 -1.208407
16  4.897806 -1.501723
17  5.462671  0.683948
18  5.386413  1.159663
19  4.958338 -0.118587
20  6.378715 -0.452547
21  4.892325 -1.136333
22  6.065894  0.172120
23  4.779468  1.060217
24  6.196348 -0.630372
25  5.878887 -0.097521
26  5.965006  0.043404
27  5.424634 -0.661314
28  5.766342  1.634305
29  4.898722  0.221017
30  5.555791 -0.344740
31  4.847733 -0.673261
32  5.016774 -1.401058
33  4.913045  0.302398
34  4.980025  0.526055
35  5.376071  1.046908
36  5.772103 -0.283880
37  6.157824 -1.267790
38  4.726864  1.374032
39  6.311262 -0.959638


In [17]:
scaler = MinMaxScaler(feature_range=(-10, 10))
model=scaler.fit(df)
scaled_data=model.transform(df)
 
# print scaled features
print(scaled_data)

[[  2.63314714  -1.80728325]
 [  5.41001337  -7.81756416]
 [  9.44834369  -9.76815472]
 [ -5.35070175  -4.28777536]
 [ -9.06787025  -2.18277611]
 [  9.7080193   -8.70554671]
 [-10.           3.38511331]
 [ -0.14983217   3.5777549 ]
 [  9.98636466   5.39013358]
 [  9.20271905  -7.11579629]
 [ -4.33142545  -4.57384921]
 [  1.64146937  -9.80132289]
 [ -7.35043952  10.        ]
 [  2.48986654  -0.62775653]
 [  4.49808749   3.71150475]
 [ -9.10966022  -8.52622662]
 [  5.28215036   2.52013279]
 [ -0.7300436    1.31505019]
 [ -5.04251735   7.04099917]
 [ -9.02545139  -9.46259295]
 [ -0.1319488   -6.00864043]
 [ 10.           6.57092382]
 [  4.67137818   4.34761389]
 [ -6.02327507   1.07268337]
 [ -8.22643265   3.41351236]
 [  1.37912049  -9.25433072]
 [  1.59154273   8.18860841]
 [  2.74756448   1.81192813]
 [  4.8335007   -0.69712884]
 [  6.96739123  -7.37418285]
 [ -5.35920555  -3.12865989]
 [  4.51269333   9.96131442]
 [ -0.4093566   -4.96784761]
 [  6.7694898   -3.27556061]
 [ -3.26931093

In [30]:
#Z score normalisation
from sklearn.preprocessing import StandardScaler 
sc = StandardScaler().fit(df) 
new2 = sc.transform(df) 
print(new2)

[[ 0.254 -0.076]
 [ 0.712 -1.022]
 [ 1.378 -1.329]
 [-1.062 -0.466]
 [-1.675 -0.135]
 [ 1.421 -1.162]
 [-1.829  0.742]
 [-0.205  0.772]
 [ 1.467  1.058]
 [ 1.337 -0.912]
 [-0.894 -0.511]
 [ 0.091 -1.334]
 [-1.392  1.783]
 [ 0.231  0.11 ]
 [ 0.562  0.793]
 [-1.682 -1.134]
 [ 0.691  0.606]
 [-0.3    0.416]
 [-1.012  1.318]
 [-1.668 -1.281]
 [-0.202 -0.737]
 [ 1.469  1.243]
 [ 0.59   0.893]
 [-1.173  0.378]
 [-1.537  0.746]
 [ 0.047 -1.248]
 [ 0.082  1.498]
 [ 0.273  0.494]
 [ 0.617  0.099]
 [ 0.969 -0.952]
 [-1.064 -0.284]
 [ 0.564  1.777]
 [-0.248 -0.573]
 [ 0.936 -0.307]
 [-0.719 -0.485]
 [ 0.78   1.363]
 [ 0.711  1.577]
 [ 1.401 -1.366]
 [ 0.399 -1.256]
 [-0.321 -1.095]]


In [5]:
df=pd.read_csv("crop_production.csv") #a csv file with crop production data
df.head(10)

State_Name  Crop_Year       Season                 Crop  \
0  Andaman and Nicobar Islands       2000  Kharif                  Arecanut   
1  Andaman and Nicobar Islands       2000  Kharif       Other Kharif pulses   
2  Andaman and Nicobar Islands       2000  Kharif                      Rice   
3  Andaman and Nicobar Islands       2000  Whole Year                Banana   
4  Andaman and Nicobar Islands       2000  Whole Year             Cashewnut   
5  Andaman and Nicobar Islands       2000  Whole Year              Coconut    
6  Andaman and Nicobar Islands       2000  Whole Year            Dry ginger   
7  Andaman and Nicobar Islands       2000  Whole Year             Sugarcane   
8  Andaman and Nicobar Islands       2000  Whole Year          Sweet potato   
9  Andaman and Nicobar Islands       2000  Whole Year               Tapioca   

      Area  Production  
0   1254.0      2000.0  
1      2.0         NaN  
2    102.0       321.0  
3    176.0       641.0  
4    720.0       165.0  
5  18168.0  65100000.0  
6     36.0         NaN  
7      1.0         2.0  
8      NaN        15.0  
9     40.0       169.0

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49 entries, 0 to 48
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   State_Name  49 non-null     object 
 1   Crop_Year   49 non-null     int64  
 2   Season      49 non-null     object 
 3   Crop        49 non-null     object 
 4   Area        47 non-null     float64
 5   Production  44 non-null     float64
dtypes: float64(2), int64(1), object(3)
memory usage: 2.4+ KB


In [7]:
df.isnull().sum()

State_Name    0
Crop_Year     0
Season        0
Crop          0
Area          2
Production    5
dtype: int64

In [11]:
#assigning df to another variable so that I can demonstrate different ways of handling missing values,
#while still having the original dataset
df1=df 
df1=df1.dropna()
df1.info()
df1.head(10)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 42 entries, 0 to 48
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   State_Name  42 non-null     object 
 1   Crop_Year   42 non-null     int64  
 2   Season      42 non-null     object 
 3   Crop        42 non-null     object 
 4   Area        42 non-null     float64
 5   Production  42 non-null     float64
dtypes: float64(2), int64(1), object(3)
memory usage: 2.3+ KB


State_Name  Crop_Year       Season                 Crop  \
0   Andaman and Nicobar Islands       2000  Kharif                  Arecanut   
2   Andaman and Nicobar Islands       2000  Kharif                      Rice   
3   Andaman and Nicobar Islands       2000  Whole Year                Banana   
4   Andaman and Nicobar Islands       2000  Whole Year             Cashewnut   
5   Andaman and Nicobar Islands       2000  Whole Year              Coconut    
7   Andaman and Nicobar Islands       2000  Whole Year             Sugarcane   
9   Andaman and Nicobar Islands       2000  Whole Year               Tapioca   
10  Andaman and Nicobar Islands       2001  Kharif                  Arecanut   
11  Andaman and Nicobar Islands       2001  Kharif       Other Kharif pulses   
14  Andaman and Nicobar Islands       2001  Whole Year              Coconut    

       Area  Production  
0    1254.0      2000.0  
2     102.0       321.0  
3     176.0       641.0  
4     720.0       165.0  
5   18168.0  65100000.0  
7       1.0         2.0  
9      40.0       169.0  
10   1254.0      2061.0  
11      2.0         1.0  
14  18190.0  64430000.0

In [13]:
df2=df
#calculating mean of production
mean_prod=df2['Production'].mean()
#calculating median for area
median_area=df2['Area'].median()

#Replacing missing Values in Production column with mean of Production
df2['Production']=df2['Production'].fillna(mean_prod)
#Replacing missing Values in Area column with mean of Area
df2['Area']=df2['Area'].fillna(median_area)

#Checkinh missing value count
df2.isnull().sum()

State_Name    0
Crop_Year     0
Season        0
Crop          0
Area          0
Production    0
dtype: int64

In [ ]:
from sklearn.preprocessing import MinMaxScaler
mms = MinMaxScaler()
df[['wt']] = mms.fit_transform(df[['x','z']])